// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"
	"github.com/Deny7676yar/Go_level2/GB_BP/internal/page"
)
import mock "github.com/stretchr/testify/mock"

// Requester is an autogenerated mock type for the Requester type
type Requester struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, url
func (_m *Requester) Get(ctx context.Context, url string) (page.Page, error) {
	ret := _m.Called(ctx, url)

	var r0 page.Page
	if rf, ok := ret.Get(0).(func(context.Context, string) page.Page); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(page.Page)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
