// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import queryfile "github.com/Deny7676yar/Go_level2/bookcsv/internal/queryfile"

// CSVReaderer is an autogenerated mock type for the CSVReaderer type
type CSVReaderer struct {
	mock.Mock
}

// ReadCSVFile provides a mock function with given fields: ctx, filepath
func (_m *CSVReaderer) ReadCSVFile(ctx context.Context, filepath string) ([]queryfile.Entry, error) {
	ret := _m.Called(ctx, filepath)

	var r0 []queryfile.Entry
	if rf, ok := ret.Get(0).(func(context.Context, string) []queryfile.Entry); ok {
		r0 = rf(ctx, filepath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queryfile.Entry)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, filepath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
